name: Deploy Next.js to ECR

on:
  push:
    branches: 
      - 'main'
jobs:
  build:
    name: Build and Deploy to AWS ECR
    runs-on: ubuntu-latest
    env:
    
          ECR_REPOSITORY: dokihealth-b2c
          IMAGE_TAG: latest
          NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
          NEXT_PUBLIC_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_PUBLISHABLE_KEY}} 
          NEXT_PUBLIC_APP_URL: ${{secrets.NEXT_PUBLIC_APP_URL}}
          NEXT_PUBLIC_PAYSTACK_MODE: ${{secrets.NEXT_PUBLIC_PAYSTACK_MODE}}
          TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
          TWILIO_API_KEY_SID: ${{secrets.TWILIO_API_KEY_SID}}
          TWILIO_API_KEY_SECRET: ${{secrets.TWILIO_API_KEY_SECRET}}
          PAYSTACK_SECRET_KEY: ${{secrets.PAYSTACK_SECRET_KEY}}
          SUPABASE_SERVICE_ROLE_KEY: ${{secrets.SUPABASE_SERVICE_ROLE_KEY}}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with: 

              aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
              aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              aws-region: ${{secrets.AWS_REGION}}
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      
      - name: Build, tag and push docker image to AWS ECR
        env:
          REGISTRY: 123507875554.dkr.ecr.eu-north-1.amazonaws.com
          REPOSITORY: dokihealth-b2c
          IMAGE_TAG: latest
          
        run: |
          docker compose build \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
            --build-arg  NEXT_PUBLIC_PUBLISHABLE_KEY=${NEXT_PUBLIC_PUBLISHABLE_KEY} \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
          docker tag dokihealth $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
